### PR TITLE
Add `buffer_opts` configuration for message caputre buffer. Rename former `buffer_opts` to `window_opts`.

### PR DESCRIPTION
**Pull request by hehelego**
- The configuration item `buffer_opts` is renamed to `window_opts`,
  which is what it actually is.
- A new configuration item `buffer_opts` is added
  to set the buffer options for the message capture scratch buffer.
- `open_float` function now returns both the window number and the buffer number.

### CODE REVIEW

**Comment by AckslD** [comment]
@hehelego, I think this makes sense but I'd prefer to not have such a breaking change. At least I would like to have a way to warn users that this breaking change will occur for some time but still support the old config.

Is there actually something that this helps solve that wasn't possible before?

**Comment by hehelego** [comment]
People tend to use `packer.nvim` to manage their neovim plugins which has a breaking change detecting and warnning feature
see [packer.nvim ReadMe notice on 2021-07-28](https://github.com/wbthomason/packer.nvim#notices).  
However, I know that many plugin managers do not have this feature.  
Also, please consider add a new branch with this patch and a branch supporting the legacy configuration.

We might find a way to smoothly migrate to the new configuration:  
Perhaps add an additional flag to indicate whether we are on a legacy config or a new config.


> @hehelego, I think this makes sense but I'd prefer to not have such a breaking change. At least I would like to have a way to warn users that this breaking change will occur for some time but still support the old config.
> 
> Is there actually something that this helps solve that wasn't possible before?

**Comment by AckslD** [comment]
@hehelego, to help me better understand, could you describe what issue this solves? Is it just renaming for more sensible structure or is there something that the old code doesn't allow you to do?

**Comment by hehelego** [comment]
> @hehelego, to help me better understand, could you describe what issue this solves? Is it just renaming for more sensible structure or is there something that the old code doesn't allow you to do?

Hi, sorry for my late response. I was busy myself for the midterm in the past week.  

This patch makes the following changes

- Rename: `buffer_opts` to `window_opts`.   
  The configuration was previously called `buffer_opts`, however what is really does it to specify the window options which are later used as parameters for `vim.api.open_win` call.
- Add a new configuration `buffer_opts` for users to specify buffer options.
- Change `settings.prepare` function to enabling setting window options and buffer options for the messages window/buffer.

Also, the `README` page, the vimdoc file are updated to adopt the changes.  
A few tests are added to verify that the `buffer_opts` works as expected.

**Pull request closed without merging**
